### ISSUE TITLE
There should be a code snippet for map decoding.

### ISSUE THREAD

**Issue by PlutarianReal** [YooHoo485/DemystifyBonk#11]
It is very dificult to decode a map as the code in the MAPFORMAT.md relies on other variables, and therefore does not run. :(
It would be nice if there was a code snippet in there where you could input the encoded map and have it decoded but I understand if this is a very dificult thing to do.

**Comment by UnmatchedBracket** [comment]
All the libraries used in the file can be accessed from NPM. I also have [a Repl](https://replit.com/@UnmatchedBracket/bonkio-is-decoder) (which i'll put in that file) to decode/encode maps and "is" data.
