### ISSUE TITLE
The Packets.md file is missing the incoming balance packet and the repository is missing an explanation on what /curate does.

### ISSUE THREAD

**Issue by PlutarianReal** [YooHoo485/DemystifyBonk#8]
Inside of the Packets.md file there is no incoming packet with id 36 which is the id of the incoming balance packet. The following is what I think should be added to the file.
[

36: Receive Balance
Example: 42[36,1,-55]
Items:
1. The Players ID of the person who will have their balance changed.
2. The balance amount.

]
I also think that an explanation of /curate would be nice as there is not much info about it and how it works online.
Thanks for reading this,
PlutarianReal

**Comment by PlutarianReal** [comment]
You do not have to credit me by the way if you do not want to.

**Comment by UnmatchedBracket** [comment]
Ack! Forgot to read GitHub notifications for a while. Sorry about that.
I'll put in the balance packet. Thanks for the info.
About the /curate, what info would I provide? There's already the request and response packets.

**Comment by PlutarianReal** [comment]
Sorry for responding so late. I think that you could add info about what the command does as I only learned about it from another bonk.io player. I think it allows admins to put maps in the chosen maps but it would be nice if there was a text file explaining it but I am not sure and an explanation in this repo would be nice if it is possible.

**Comment by UnmatchedBracket** [comment]
> I think it allows admins to put maps in the chosen maps but it would be nice if there was a text file explaining it but I am not sure and an explanation in this repo would be nice if it is possible.
Indeed, I'm pretty sure that is what it does. However, the thing with having an explanation here is that /curate is completely useless for normal users, and the curators already know how to use it, making such a document rather useless.

**Comment by PlutarianReal** [comment]
That makes sense.
